global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cpc-web'
    static_configs:
      - targets: ['web.railway.internal:8080']

  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['otel-collector.railway.internal:9464']

  - job_name: 'dramatiq'
    metrics_path: /
    static_configs:
      - targets: ['worker.railway.internal:9191'] 
